project_id = "hxbemcmmnbxsvnmyzoee"

[functions.send-match-notification]
verify_jwt = true

[functions.ai-match-parts]
verify_jwt = true

[functions.parse-parts-pdf]
verify_jwt = true

[functions.parse-parts-text]
verify_jwt = true

[functions.log-security-event]
verify_jwt = false

[functions.auto-match-parts]
verify_jwt = true
